"""make a few collumns nullable

Revision ID: 2826ff1f140b
Revises: 9bae2ffcd4ce
Create Date: 2025-04-13 20:10:33.612468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2826ff1f140b'
down_revision: Union[str, None] = '9bae2ffcd4ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'subject_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('schedule', 'teacher_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('schedule', 'classroom_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('schedule', 'group_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'group_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('schedule', 'classroom_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('schedule', 'teacher_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('schedule', 'subject_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
