"""replace type String with Date in periods

Revision ID: 5179b1f7df9d
Revises: 2826ff1f140b
Create Date: 2025-04-15 22:20:01.468949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5179b1f7df9d'
down_revision: Union[str, None] = '2826ff1f140b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE periods")
    op.alter_column('periods', 'begin',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               postgresql_using="begin::date",
               existing_nullable=False)
    op.alter_column('periods', 'end',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               postgresql_using="begin::date",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('periods', 'end',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('periods', 'begin',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
