"""lesson time column drop

Revision ID: 8d8ca33f8765
Revises: 5179b1f7df9d
Create Date: 2025-04-15 23:29:13.203043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8ca33f8765'
down_revision: Union[str, None] = '5179b1f7df9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schedule_lesson_time_id_fkey', 'schedule', type_='foreignkey')
    op.create_foreign_key(None, 'schedule', 'times', ['lesson_number'], ['number'])
    op.drop_column('schedule', 'lesson_time_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('lesson_time_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.create_foreign_key('schedule_lesson_time_id_fkey', 'schedule', 'times', ['lesson_time_id'], ['number'])
    # ### end Alembic commands ###
