"""times rework

Revision ID: 9bae2ffcd4ce
Revises: 4c1322c2cd5f
Create Date: 2025-04-13 19:43:15.660100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bae2ffcd4ce'
down_revision: Union[str, None] = '4c1322c2cd5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periods', sa.Column('id', sa.String(), nullable=False))
    op.add_column('periods', sa.Column('begin', sa.String(), nullable=False))
    op.add_column('periods', sa.Column('end', sa.String(), nullable=False))
    op.drop_column('periods', 'period')
    op.drop_column('periods', 'prefix')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periods', sa.Column('prefix', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('periods', sa.Column('period', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('periods', 'end')
    op.drop_column('periods', 'begin')
    op.drop_column('periods', 'id')
    # ### end Alembic commands ###
