"""create hashes table

Revision ID: f71246b047c9
Revises: 8d8ca33f8765
Create Date: 2025-04-17 03:20:57.774123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f71246b047c9'
down_revision: Union[str, None] = '8d8ca33f8765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('exchanges', sa.String(), nullable=True),
    sa.Column('teachers', sa.String(), nullable=True),
    sa.Column('subjects', sa.String(), nullable=True),
    sa.Column('classes', sa.String(), nullable=True),
    sa.Column('rooms', sa.String(), nullable=True),
    sa.Column('classgroups', sa.String(), nullable=True),
    sa.Column('periods', sa.String(), nullable=True),
    sa.Column('lesson_times', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hashes')
    # ### end Alembic commands ###
